import type { Metadata } from "next";
import { Darker_Grotesque } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/_Navbar";
import Script from "next/script";
import Head from "next/head";

const darker_grotesque = Darker_Grotesque({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-darker-grotesque'
});

const inter = Inter({ 
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-inter'
 });


export const metadata: Metadata = {
  title: "JOSHUA VILLALOBOS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <Script src="navbar-scripts.js"/>
      </Head>
      <body className={ `${inter.variable} ${darker_grotesque.variable} bg-stone-900 px-5` }>
        <main>
            {children}
        </main>
      </body>
    </html>
  );
}
